name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: "linux/amd64, windows/amd64"
          name: "gam"
          compress: "true"
          dest: "dist"

      - run: echo "RELEASE_VERSION=`git tag | sort -V | tail -1`" >> $GITHUB_ENV

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: Release ${{ env.RELEASE_VERSION }}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ env.RELEASE_VERSION }}
          files: |
            gam
